### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by ehabdevel** [oxyii/react-native-web-swiper#2] opened 2019-03-20 19:30 UTC
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function onStartShouldSetResponder(e) {
        return config.onStartShouldSetPanResponder === undefined ? fals...<omitted>... } could not be cloned.
![swip](https://user-images.githubusercontent.com/20784706/54713428-3da56c00-4b57-11e9-87a8-2d78675d733a.PNG)

**Comment by oxyii** [comment] 2019-03-20 19:51
@ehabdevel Thanks for your report.

Can you share your sources? The fact is that the swiper does not use `onStartShouldSetPanResponder` in `PanResponder` object.

**Comment by ehabdevel** [comment] 2019-03-20 21:11
@oxyii here is my package.json 

{
  "version": "0.1.0",
  "private": true,
  "main": "./App.js",
  "dependencies": {
    "expo": "^32.0.6",
    "react": "^16.8.4",
    "react-art": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-native": "^0.59.1",
    "react-native-web": "^0.11.1",
    "react-native-web-swiper": "^1.10.0",
    "react-scripts": "2.1.8"
  },
  "scripts": {
    "start-web": "react-scripts start",
    "build-web": "react-scripts build",
    "test-web": "react-scripts test",
    "eject-web": "react-scripts eject",
    "start-native": "expo start",
    "android": "expo android",
    "ios": "expo ios",
    "build:ios": "expo build:ios",
    "build:android": "expo build:android"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-expo": "^5.1.1"
  }
}

**Comment by oxyii** [comment] 2019-03-20 21:16
@ehabdevel No. Please share file contents where swiper includes. I think you trying to include some `PanResponder` into some slide....

**Comment by ehabdevel** [comment] 2019-03-20 21:27
@oxyii it is new app created with npx create-react-app

Here is my App.js file:

import React from "react";
import { AppRegistry, StyleSheet, View } from "react-native";
import Screen from "./component/screen";

class App extends React.Component {
  render() {
    return (
      <View style={styles.appContainer}>
        <Screen />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  appContainer: {
    flex: 1
  }
});

AppRegistry.registerComponent("App", () => App);

export default App;


And here is the file where swiper is: 

import React from "react";
import { View, Text, StyleSheet } from "react-native";
import Swiper from "react-native-web-swiper";

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  slideContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center"
  },
  slide1: {
    backgroundColor: "rgba(20,20,200,0.3)"
  },
  slide2: {
    backgroundColor: "rgba(20,200,20,0.3)"
  },
  slide3: {
    backgroundColor: "rgba(200,20,20,0.3)"
  }
});

export default class Screen extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Swiper>
          <View style={[styles.slideContainer, styles.slide1]}>
            <Text>Slide 1</Text>
          </View>
          <View style={[styles.slideContainer, styles.slide2]}>
            <Text>Slide 2</Text>
          </View>
          <View style={[styles.slideContainer, styles.slide3]}>
            <Text>Slide 3</Text>
          </View>
        </Swiper>
      </View>
    );
  }
}

**Comment by ehabdevel** [comment] 2019-03-20 21:33
I just copy past the example what exist in the Readme file

**Comment by oxyii** [comment] 2019-03-20 21:40
@ehabdevel Please use [markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for code sharing or do you have the repo (with minimal code to reproduce the issue) that can you share?

**Comment by ehabdevel** [comment] 2019-03-20 21:45
Ok, but if you say that the swiper does not use onStartShouldSetPanResponder in PanResponder object.
So I this message may belong to the ( React Developer Tools ) Extensions for google chrome. 
at beginning when I run it (npm run start-web) it does not show anything in the console or in the page but when I try to investigate with React Developer Tools  It shows this message in the console.

**Comment by ehabdevel** [comment] 2019-03-20 21:51
here is the repo https://github.com/ehabdevel/swipertest

**Comment by oxyii** [comment] 2019-03-20 21:52
@ehabdevel Nope. Cannot reproduce. Console is clean

![Выделение_001](https://user-images.githubusercontent.com/39907210/54721619-8408c400-4b73-11e9-81be-8aedb45a5c60.png)

**Comment by oxyii** [comment] 2019-03-20 21:57
@ehabdevel It's repo without swiper. I asked repo with code to reproduce.

**Comment by ehabdevel** [comment] 2019-03-20 22:05
Yes updated, and I even tried to copy the file outside the component screen.js

**Comment by ehabdevel** [comment] 2019-03-20 22:31
![swip2](https://user-images.githubusercontent.com/20784706/54723574-a6e5a900-4b70-11e9-8719-156c548d4ce7.PNG)

**Comment by oxyii** [comment] 2019-03-20 22:55
@ehabdevel On your last screenshot I don't see errors in console. All works fine I think.

About white screen. Look: All your DOM-tree have `{flex:1}` style but your react root tag is with no styles. It means empty tag have no height! You need to set height of root tag. Add styles below into `<head>` tag of `public/index.html`

```html
<style>
    html, body {
        height: 100%;
    }
    body {
        overflow: hidden;
    }
    #root {
        display: flex;
        height: 100%;
    }
</style>
```

that's not all

> it is new app created with npx create-react-app

This is not a best way to create react-**native** app. Follow instructions from [official RN docs](https://facebook.github.io/react-native/docs/getting-started) then install deps following instructions on [RNWeb docs](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md).

All works fine, I close this issue. Screenshot below - it's your repo with styles definitions above

![Выделение_001](https://user-images.githubusercontent.com/39907210/54724438-3e042e00-4b7c-11e9-89ee-47326eea9dcf.png)

**Closed by oxyii** 2019-03-20 22:55 UTC
Labels: help wanted

**Comment by oxyii** [comment] 2019-03-20 22:58
@ehabdevel Or you can use [CRNWA](https://github.com/orYoffe/create-react-native-web-app) as alternate. But anyway don't forget to add `<style>` to html. Good luck!

**Comment by ehabdevel** [comment] 2019-03-20 23:00
Many thanks for your help.
