### ISSUE TITLE
How to render dynamic image links?

### ISSUE THREAD

**Issue by zizango123** [oxyii/react-native-web-swiper#15] opened 2019-08-16 05:05 UTC
I have tried many times to render image dynamically in the swipper using image code as below

<Image source={{uri: sellerimageURL+'/image2/'+this.state.productDetails.image_2}} style={{height: '100%', width: '100%'}} />

this code works on any other component except inside the swiper.

Any suggestion how this can be loaded.

**Comment by oxyii** [comment] 2019-08-16 05:15
@zizango123 thanks for you report. Can you share more detailed code? And why you use `{ width: 100%, height: 100% }` instead `{ flex: 1 }`?

**Comment by zizango123** [comment] 2019-08-16 05:31
{flex: 1}  do works, its just a test for my code that i use { width: 100%, height: 100% } to differentiate  (if any) occurs. 

`<Swiper
                    minDistanceForAction={0.1}
                    controlsProps={{
                      dotsTouchable: true,
                      prevPos: 'left',
                      nextPos: 'right',
                      nextTitle: '>',
                      nextTitleStyle: { color: 'red', fontSize: 24, fontWeight: '500' },
                      PrevComponent: ({ onPress }) => (
                        <TouchableOpacity onPress={onPress}>
                          <Text style={{ color: 'red', fontSize: 24, fontWeight: '500' }}>
                            {'<'}
                          </Text>
                        </TouchableOpacity>
                      ),
                    }}
                  >
            <Image source={{uri: 'http://placeimg.com/640/500/animal'}} style={{flex: 1}} /> //this works well
            <Image source={{uri: sellerimageURL+'/image3/'+this.state.productDetails.image_3}} style={{flex: 1}} />  //this doesn't
            <Image source={{uri: sellerimageURL+'/image4/'+this.state.productDetails.image_4}} style={{flex: 1}} />
         </Swiper>`

in the above code snippet **sellerimageURL** is a constant and **this.state.productDetails** is derived from an api.

Direct image link works well but not the dynamic link. The swiper doesn't re-render with the appropriate content.

**Comment by oxyii** [comment] 2019-08-16 10:37
@zizango123 Reproduced. Swiper does not re-render content when changing props / state. But slide can re-render him-self. Please separate your dynamic slide into component. Something like [this](https://snack.expo.io/@oxyii/rnws-dynamic-content).

I'm not sure that this is a bug. I think dynamic content in the slider will not be a common situation.

**Comment by brilliantinsane** [comment] 2019-08-16 22:13
So you can not use map inside render?

Smth like this:

`
<View style={styles.container}>
     <Swiper
        loop={true}
        minDistanceToCapture={0}
     >
          {children.map((t, i) => {
            return (
              <View key={i}>
                <Image source={{ uri: `https://image.tmdb.org/t/p/original/${t.backdrop_path}` }} style={{ width: DEVICE_WIDTH, height: 250 }} />
              </View>
            )
          })}
     </Swiper>
</View>
`

Where DEVICE_WIDTH is `Dimensions.get('window').width`, and `children` is an array of objects.

**Comment by oxyii** [comment] 2019-08-16 23:45
@brilliantinsane see [snack](https://snack.expo.io/BJ2sn24Er). I don't know your case but I think something wrong with your `children.backdrop_path`.

**Comment by brilliantinsane** [comment] 2019-08-17 08:17
Alright, thanks for the answer, I figured it out.
I had to create a new array with 'dry' URL's instead of pulling an URL from some object.

Something worth mentioning, since I'm here, while testing I noticed some considerable glitches when it comes to swiping left or right, like it's swiping (or rather rendering) pixel by pixel, I don't know why is this happening but when I delete the app and rebuild it, then it works fine.

I've spent far too many days on searching for a GOOD react-native swiper, and so far, I think this is the best one, so keep it up, please! :)

**Comment by oxyii** [comment] 2019-08-17 08:41
@brilliantinsane 

> while testing I noticed some considerable glitches when it comes to swiping left or right, like it's swiping (or rather rendering) pixel by pixel

I noticed similar glitches when in the content of the slides there were large and heavy SVGs. I think with pictures of initially large sizes something similar can be observed.
Also please check how many times your swiper and its content are rendered. Perhaps your props or state changes several times. This leads to an extra render.
Anyway feel free to create a issue in case of problems.

> I think this is the best one

Thank you very much

> so keep it up, please

This swiper will be part of `react-native-elements` [soon](https://github.com/react-native-training/react-native-elements/pull/1981) I hope

**Comment by oxyii** [comment] 2019-08-17 09:46
@zizango123 I close this issue. Please comment if still actual

**Closed by oxyii** 2019-08-17 09:46 UTC
Labels: help wanted, question

**Comment by schellack** [comment] 2019-09-14 00:00
> Swiper does not re-render content when changing props / state.

Does this mean it's not possible to dynamically add `<View>`s to the Swiper @oxyii ? I don't mean to re-render a view's content, I mean to actually add another view based on state.

**Comment by oxyii** [comment] 2019-09-14 05:49
@schellack No for now. Exactly no without remount. #22
